name: Build and Push Optimized Docker Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: sobkawy81
          password: sobki81@DOCKER
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile   
          push: true
          tags: sobkawy81/todo-nodejs:latest
          cache-from: type=registry,ref=sobkawy81/todo-nodejs:cache
          cache-to: type=registry,ref=sobkawy81/todo-nodejs:cache,mode=max
          platforms: linux/amd64,linux/arm64
